AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create the IAM Role GreengrassV2TokenExchangeRole and IoT role alias.'

Resources:
  GreengrassV2TokenExchangeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'GreengrassV2TokenExchangeRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'credentials.iot.amazonaws.com'
            Action: 'sts:AssumeRole'

  GreengrassV2TokenExchangeRoleAlias:
    Type: 'AWS::IoT::RoleAlias'
    Properties:
      RoleAlias: 'GreengrassV2TokenExchangeRoleAlias'
      RoleArn: !GetAtt GreengrassV2TokenExchangeRole.Arn
