---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This example component shows how to publish and subscribe to IoT Core topics from a component."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Topic: "/topic/{iot:thingName}"
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.example.IoTPubSub:mqttproxy:1:
          policyDescription: Allows access to publish and subscribe to IoT Core topic /topic/{iot:thingName}.
          operations:
            - aws.greengrass#SubscribeToIoTCore
            - aws.greengrass#PublishToIoTCore
          resources:
            - "/topic/{iot:thingName}"
            - "/topic/{iot:thingName}/#"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.example.IoTPubSub.zip"
        Unarchive: ZIP
    Lifecycle:
      Run: "PYTHONPATH={artifacts:decompressedPath}/com.example.IoTPubSub/dependencies python3 -u {artifacts:decompressedPath}/com.example.IoTPubSub/main.py {configuration:/Topic}"
