---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This example component shows how to publish and subscribe to local topics from a component."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Topic: "/topic/{iot:thingName}"
    Message: "Hello from local pubsub topic."
    accessControl:
      aws.greengrass.ipc.pubsub:
        com.example.LocalPubSub:pubsub:1:
          policyDescription: Allows access to publish and subscribe to local topic /topic/{iot:thingName}.
          operations:
            - aws.greengrass#SubscribeToTopic
            - aws.greengrass#PublishToTopic
          resources:
            - "/topic/{iot:thingName}"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.example.LocalPubSub.zip"
        Unarchive: ZIP
    Lifecycle:
      Run: "PYTHONPATH={artifacts:decompressedPath}/com.example.LocalPubSub/dependencies python3 -u {artifacts:decompressedPath}/com.example.LocalPubSub/main.py {configuration:/Topic} {configuration:/Message}"
